### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by chrispelzer** [waynestate/base-site#3]
Figure out what we want to have in the CONTRIBUTING.md to allow others to easily contribute.

**Comment by nickdenardis** [comment]
Helpful context of other similar packages contributing guidelines:

* https://github.com/blog/1184-contributing-guidelines
* https://help.github.com/articles/setting-guidelines-for-repository-contributors/
* https://gist.github.com/PurpleBooth/b24679402957c63ec426
* https://github.com/thoughtbot/suspenders/blob/master/CONTRIBUTING.md
* https://github.com/spatie/blender#contributing
* https://github.com/sahat/hackathon-starter#contributing
* https://github.com/bevry/base/blob/master/CONTRIBUTING.md
* https://github.com/fs/rails-base/blob/master/CONTRIBUTING.md
