### ISSUE TITLE
Upgrade stylelint from v13 to v16

### ISSUE THREAD

**Issue by chrispelzer** [waynestate/base-site#634]
Upgrade stylelint from v13 to v16, since we use NodeJS 20, stylelint v16 is the one that it supports.

Last comment was that it was breaking our setup in [July 2023](https://github.com/waynestate/base-site/pull/632#issuecomment-1636188297), it might be better nowadays. We can try again.

---

migration guide from v13 -> v14: https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md

migration guide from v14 -> v15: https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md

migration guide from v15 -> v16: https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-16.md

**Comment by nickdenardis** [comment]
This PR looks to be merged. Closing.
